const SAMPLES_DB = {
  SNARE: [
    'Samples/Snares/Snare [BASEMENT] @stxrm808.wav',
    'Samples/Snares/Snare [BLOCK] @stxrm808.wav',
    'Samples/Snares/Snare [COLD] @stxrm808.wav',
    'Samples/Snares/Snare [CRUNCH] @stxrm808.wav',
    'Samples/Snares/Snare [FACTORY] @stxrm808.wav',
    'Samples/Snares/Snare [GHOST] @stxrm808.wav',
    'Samples/Snares/Snare [HARSH] @stxrm808.wav',
    'Samples/Snares/Snare [MARY] @stxrm808.wav',
    'Samples/Snares/Snare [OLD] @stxrm808.wav',
    'Samples/Snares/Snare [QUICK] @stxrm808.wav',
    'Samples/Snares/Snare [RABONA] @stxrm808.wav',
    'Samples/Snares/Snare [ROLI] @stxrm808.wav',
    'Samples/Snares/Snare [SNAP] @stxrm808.wav',
    'Samples/Snares/Snare [TR] @stxrm808.wav',
    'Samples/Snares/Snare [TYPE] @stxrm808.wav'
  ],
  CLAP: [
    'Samples/Claps/Clap [BLOXX] @stxrm808.wav',
    'Samples/Claps/Clap [COUNTER] @stxrm808.wav',
    'Samples/Claps/Clap [CRISP] @stxrm808.wav',
    'Samples/Claps/Clap [CUT] @stxrm808.wav',
    'Samples/Claps/Clap [GOSPEL] @stxrm808.wav',
    'Samples/Claps/Clap [HARSH] @stxrm808.wav',
    'Samples/Claps/Clap [ORIGINAL] @stxrm808.wav',
    'Samples/Claps/Clap [REAL] @stxrm808.wav',
    'Samples/Claps/Clap [RETRO] @stxrm808.wav'
  ],
  HIHAT: [
    'Samples/Hi Hats/Hi Hat [BIG] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [BOOM] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [CHROM] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [DIOR] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [FAV] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [NICE] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [NOISE] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [OPEN] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [PERC] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [PRADA] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [REAL] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [ROOM] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SEC] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SHAKE] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SHIMMER] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SHORT] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SIDE] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [SMOKE] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [TIME] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [TINY] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [TRAP] @stxrm808.wav',
    'Samples/Hi Hats/Hi Hat [iMAC] @stxrm808.wav'
  ],
  'OPEN HAT': [
    'Samples/Open Hats/Open Hat [LIGHT] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [ORIGINAL] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [REAL] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [REPLICA] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [SHORT] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [SLIDE] @stxrm808.wav',
    'Samples/Open Hats/Open Hat [SMALL] @stxrm808.wav'
  ],
  '808': [
    'Samples/808s/808 [ANALOG] @stxrm808.wav',
    'Samples/808s/808 [AP] @stxrm808.wav',
    'Samples/808s/808 [BASS] @stxrm808.wav',
    'Samples/808s/808 [BLOXX] @stxrm808.wav',
    'Samples/808s/808 [BOUNCE] @stxrm808.wav',
    'Samples/808s/808 [CRUNCH] @stxrm808.wav',
    'Samples/808s/808 [CTM] @stxrm808.wav',
    'Samples/808s/808 [DARK] @stxrm808.wav',
    'Samples/808s/808 [DECAP] @stxrm808.wav',
    'Samples/808s/808 [EASY] @stxrm808.wav',
    'Samples/808s/808 [EMPTY] @stxrm808.wav',
    'Samples/808s/808 [GIFT] @stxrm808.wav',
    'Samples/808s/808 [HAWK] @stxrm808.wav',
    'Samples/808s/808 [LONG] @stxrm808.wav',
    'Samples/808s/808 [PRO] @stxrm808.wav',
    'Samples/808s/808 [ROLEX] @stxrm808.wav',
    'Samples/808s/808 [ROLI] @stxrm808.wav',
    'Samples/808s/808 [SAUCE] @stxrm808.wav',
    'Samples/808s/808 [SHAKE] @stxrm808.wav',
    'Samples/808s/808 [SOFT] @stxrm808.wav',
    'Samples/808s/808 [SPIN] @stxrm808.wav',
    'Samples/808s/808 [TIMBO] @stxrm808.wav',
    'Samples/808s/808 [TRICK] @stxrm808.wav',
    'Samples/808s/808 [TRUNK] @stxrm808.wav',
    'Samples/808s/808 [TWIN] @stxrm808.wav',
    'Samples/808s/808 [WALL] @stxrm808.wav',
    'Samples/808s/808 [WAVE] @stxrm808.wav',
    'Samples/808s/808 [WING] @stxrm808.wav',
    'Samples/808s/808 [WOMP] @stxrm808.wav',
    'Samples/808s/808 [WOOD] @stxrm808.wav',
    'Samples/808s/808 [ZPINS II] @stxrm808.wav',
    'Samples/808s/808 [ZPINS] @stxrm808.wav',
    'Samples/808s/808 [ZRAY] @stxrm808.wav'
  ],
  PERC: [
    'Samples/Percs/Perc [2_3] @stxrm808.wav',
    'Samples/Percs/Perc [BAE] @stxrm808.wav',
    'Samples/Percs/Perc [BAILE] @stxrm808.wav',
    'Samples/Percs/Perc [BATTERY] @stxrm808.wav',
    'Samples/Percs/Perc [BONGO] @stxrm808 2.wav',
    'Samples/Percs/Perc [BONGO] @stxrm808.wav',
    'Samples/Percs/Perc [BOOK] @stxrm808.wav',
    'Samples/Percs/Perc [CHANT] @stxrm808.wav',
    'Samples/Percs/Perc [CLAPPY] @stxrm808.wav',
    'Samples/Percs/Perc [CLAPS] @stxrm808.wav',
    'Samples/Percs/Perc [CLEAN] @stxrm808.wav',
    'Samples/Percs/Perc [CRANK] @stxrm808.wav',
    'Samples/Percs/Perc [CRATE] @stxrm808.wav',
    'Samples/Percs/Perc [DESERT] @stxrm808.wav',
    'Samples/Percs/Perc [DIRT] @stxrm808.wav',
    'Samples/Percs/Perc [DROP] @stxrm808.wav',
    'Samples/Percs/Perc [FLAME] @stxrm808.wav',
    'Samples/Percs/Perc [FLINT III] @stxrm808.wav',
    'Samples/Percs/Perc [FLINT II] @stxrm808.wav',
    'Samples/Percs/Perc [FLINT] @stxrm808.wav',
    'Samples/Percs/Perc [LIFT] @stxrm808.wav',
    'Samples/Percs/Perc [LIGHT] @stxrm808.wav',
    'Samples/Percs/Perc [LOG DRUM] @stxrm808.wav',
    'Samples/Percs/Perc [MINI] @stxrm808.wav',
    'Samples/Percs/Perc [OHIO] @stxrm808.wav',
    'Samples/Percs/Perc [OK] @stxrm808.wav',
    'Samples/Percs/Perc [OWN] @stxrm808.wav',
    'Samples/Percs/Perc [PAGE] @stxrm808.wav',
    'Samples/Percs/Perc [PERC] @stxrm808.wav',
    'Samples/Percs/Perc [PLOP] @stxrm808.wav',
    'Samples/Percs/Perc [REC] @stxrm808.wav',
    'Samples/Percs/Perc [RIM] @stxrm808.wav',
    'Samples/Percs/Perc [RISE] @stxrm808.wav',
    'Samples/Percs/Perc [SHAKE IIII] @stxrm808.wav',
    'Samples/Percs/Perc [SHAKE III] @stxrm808.wav',
    'Samples/Percs/Perc [SHAKE II] @stxrm808.wav',
    'Samples/Percs/Perc [SHAKE I] @stxrm808.wav',
    'Samples/Percs/Perc [SICK] @stxrm808.wav',
    'Samples/Percs/Perc [STICK] @stxrm808.wav',
    'Samples/Percs/Perc [TALK] @stxrm808.wav',
    'Samples/Percs/Perc [TAMB] @stxrm808.wav',
    'Samples/Percs/Perc [UNIVERSAL] @stxrm808.wav'
  ],
  FX: [
    'Samples/Fx/Fx [2PAC] @stxrm808.wav',
    'Samples/Fx/Fx [BOY] @stxrm808.wav',
    'Samples/Fx/Fx [CROWD] @stxrm808.wav',
    'Samples/Fx/Fx [CUT] @stxrm808.wav',
    'Samples/Fx/Fx [DIST] @stxrm808.wav',
    'Samples/Fx/Fx [GLASS] @stxrm808.wav',
    'Samples/Fx/Fx [HIT 1] @stxrm808.wav',
    'Samples/Fx/Fx [HIT 2] @stxrm808.wav',
    'Samples/Fx/Fx [HIT 3] @stxrm808.wav',
    'Samples/Fx/Fx [HIT 4] @stxrm808.wav',
    'Samples/Fx/Fx [HORN] @stxrm808.wav',
    'Samples/Fx/Fx [IMPORTANT] @stxrm808.wav',
    'Samples/Fx/Fx [MILITARY] @stxrm808.wav',
    'Samples/Fx/Fx [MORTAL] @stxrm808.wav',
    'Samples/Fx/Fx [OH] @stxrm808.wav',
    'Samples/Fx/Fx [ORCA] @stxrm808.wav',
    'Samples/Fx/Fx [PSYCHO] @stxrm808.wav',
    'Samples/Fx/Fx [REV] @stxrm808.wav',
    'Samples/Fx/Fx [RISER] @stxrm808.wav',
    'Samples/Fx/Fx [SCRATCH 1] @stxrm808.wav',
    'Samples/Fx/Fx [SCRATCH 2] @stxrm808.wav',
    'Samples/Fx/Fx [SHATTER] @stxrm808.wav',
    'Samples/Fx/Fx [STRINGS] @stxrm808.wav',
    'Samples/Fx/Fx [SWOOSH] @stxrm808.wav',
    'Samples/Fx/Fx [SYNTH] @stxrm808.wav',
    'Samples/Fx/Fx [WOO] @stxrm808.wav'
  ],
  VOX: [
    'Samples/Fills/Fill [ARMY] @stxrm808.wav',
    'Samples/Fills/Fill [KIT] @stxrm808.wav',
    'Samples/Fills/Fill [SCRATCH] @stxrm808.wav',
    'Samples/Fills/Fill [SCRATS] @stxrm808.wav',
    'Samples/Fills/Fill [STRINGS] @stxrm808.wav',
    'Samples/Fills/Fill [VINYL] @stxrm808.wav'
  ],
  SYNTH: [
    'Samples/Samples/@stxrm808 - Plattenbau (101 bpm) G# minor.wav',
    'Samples/Samples/@stxrm808 - anthrazit (103 bpm) E minor.wav',
    'Samples/Samples/@stxrm808 - bricks (111 bpm) D minor.wav',
    'Samples/Samples/@stxrm808 - days (152 bpm) A# minor.wav',
    'Samples/Samples/@stxrm808 - detail (112 bpm) G# minor.wav',
    'Samples/Samples/@stxrm808 - dirt (97 bpm) A# minor.wav',
    'Samples/Samples/@stxrm808 - eternity (107).wav',
    'Samples/Samples/@stxrm808 - face (162 bpm) A minor.wav',
    'Samples/Samples/@stxrm808 - fr (107 bpm) D# minor.wav',
    'Samples/Samples/@stxrm808 - guns (105 bpm).wav',
    'Samples/Samples/@stxrm808 - high five (95 bpm) B minor.wav',
    'Samples/Samples/@stxrm808 - in a minute (100 bpm) D# minor.wav',
    'Samples/Samples/@stxrm808 - kante (101 bpm) A# minor.wav',
    'Samples/Samples/@stxrm808 - maybach (126 bpm) E minor.wav',
    'Samples/Samples/@stxrm808 - megatron (104 bpm).wav',
    'Samples/Samples/@stxrm808 - november (119 bpm) F# minor.wav',
    'Samples/Samples/@stxrm808 - omega (107 bpm) C# minor.wav',
    'Samples/Samples/@stxrm808 - osu (100 bpm) D# minor.wav',
    'Samples/Samples/@stxrm808 - oxid (199 bpm) B minor.wav',
    'Samples/Samples/@stxrm808 - paranoia (95 bpm) C minor.wav',
    'Samples/Samples/@stxrm808 - play (100 bpm) E minor.wav',
    'Samples/Samples/@stxrm808 - psychose (95 bpm) A# minor.wav',
    'Samples/Samples/@stxrm808 - push (95 bpm) D minor.wav',
    'Samples/Samples/@stxrm808 - ripped (146 bpm) C# minor.wav',
    'Samples/Samples/@stxrm808 - royce (97 bpm) C# minor.wav',
    'Samples/Samples/@stxrm808 - san andreas (98 bpm) D# minor.wav',
    'Samples/Samples/@stxrm808 - still (93 bpm) D minor.wav',
    'Samples/Samples/@stxrm808 - switch (92 bpm) C# minor.wav',
    'Samples/Samples/@stxrm808 - thotties (134 bpm) B minor.wav',
    'Samples/Samples/@stxrm808 - tokat (110 bpm) D# minor.wav',
    'Samples/Samples/@stxrm808 - tunnelblick (97 bpm) B minor.wav',
    'Samples/Samples/@stxrm808 - yakary (185 bpm) B minor.wav'
  ]
};
